restaurant:
  name: French restaurant
  capacity: 75
  description: "Name: ${restaurant.name}. Capacity: ${restaurant.capacity}. Owner: ${restaurant.owner:Andrew}"
  menu:
    itemsString: Spaghetti,Caesar,Salmon
